version: '2'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080

  userloginservice:
    build: user-login-service
    restart: always
    network_mode: "host"
    depends_on:
      - eureka-server
      - zuul-api
      - config-service
      - mysqldb
    ports:
      - 8088:8088

  writeareviewservice:
    build: write-a-review-service
    restart: always
    network_mode: "host"
    depends_on:
      - eureka-server
      - zuul-api
      - config-service
      - mysqldb
    ports:
      - 8089:8089

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logindb
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"
    volumes:
      - $HOME/data/datasql:/var/lib/mysql
    network_mode: "host"
    hostname: localhost
    restart: always

  mongodb:
    image: mongo:3.4-xenial
    restart: always
    network_mode: host
    volumes:
      - ./registration:/data/db

  reviewerprofileservice:
    build: reviewer-profile-service
    restart: always
    network_mode: "host"
    depends_on:
      - eureka-server
      - zuul-api
      - config-service
    ports:
      - 8087:8087