version: '2'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080

  userloginservice:
    build: user-login-service
    restart: always
    network_mode: "host"
    depends_on:
      - mysqldb
    ports:
      - 8088:8088

  reviewservice:
    build: review-service
    restart: always
    network_mode: "host"
    depends_on:
      - mongodb
    ports:
      - 8089:8089

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logindb
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - $HOME/data/datasql:/var/lib/mysql
    network_mode: "host"
    hostname: localhost
    restart: always

  mongodb:
    image: mongo:3.4-xenial
    restart: always
    network_mode: host
    volumes:
      - ./registration:/data/db

  reviewerprofileservice:
    build: reviewer-profile-service
    restart: always
    network_mode: "host"
    depends_on:
      - mongodb
    ports:
      - 8087:8087

  productownerprofileservice:
    build: productOwner-service
    restart: always
    network_mode: "host"
    depends_on:
      - mongodb
    ports:
      - 8060:8060

<<<<<<< HEAD
  nlpservice:
    build: NLP-service
    restart: always
    network_mode: "host"
    depends_on:
      - mongodb
    ports:
      - 8877:8877
=======
  productsearchservice:
      build: product-search-service
      restart: always
      network_mode: "host"
      depends_on:
        - mongodb
      ports:
        - 8081:8081

>>>>>>> 35c3f9a30a4df7a6e4f259c6fff8bbd2cb1b0853

  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: localhost
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST:

